#!/bin/bash

export ENV="$( cd "$( dirname "$0" )" && pwd )"

source "${ENV}/scripts/log.sh"
source "${ENV}/scripts/kconfig.sh"

cd ${ENV}
kconfig-mconf "${ENV}/Kconfig"

if [ -f ${CFG} ]; then
  toolchain setup
fi
