#!/bin/bash

export ENV="$( cd "$( dirname "$0" )" && pwd )"

source "${ENV}/scripts/log.sh"
source "${ENV}/scripts/kconfig.sh"

cd ${ENV}
mconf "${ENV}/toplevel.cfg"

if [ -f ${CFG} ]; then
  ${ENV}/scripts/toolchain setup
fi
