#!/bin/bash

source $_DT/lib/include
source $_DT/lib/config
source $_DT/lib/toolchain

usage() {
  echo "usage: dt config [[-d <device>] <profile>]"
  echo
  echo "   TODO"
  echo
  exit 1
}

find_project() {
  d=$(pwd)
  while [[ -n $d ]]; do
    if [[ -f $d/.dtproject ]]; then
      break
    fi
    d=${d%/*}
  done
  echo -n "$d"
}

copy_profile() {
  if [[ $1 == *_default ]]; then
    echo "not allowed"
    exit 1
  fi

  if [[ ! -f $_DT/profiles/$2 ]]; then
    echo "no default"
    exit 1
  fi

  cp "$_DT/profiles/$2" "$_DT/profiles/$1"
}

config_profile() {
  local config
  if [[ $1 == *_default ]]; then
    echo "not allowed"
    exit 1
  fi

  config=$(profile_config $1)
  mconf "$config" "$_DT/profile.cfg"
  prepare_toolchain $1
}

config_project() {
  project=$(find_project)
  if [[ -z $project ]]; then
    echo "no project found"
    exit 1
  fi
}

if [[ $help ]]; then
  usage
fi

while getopts ":d:" opt; do
  case $opt in
    d)
      default_profile=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done

shift $((OPTIND-1))

if [[ $# -gt 1 ]]; then
  usage
elif [[ $# -eq 1 ]]; then
  profile=$1
  if [[ $default_profile ]]; then
    copy_profile "$profile" "${default_profile}_default"
  else
    config_profile "$profile"
  fi
else
  if [[ $default_profile ]]; then
    usage
  fi
  config_project
fi

