#!/bin/bash

if [[ ${BASH_SOURCE[0]} = $0 || ${BASH_SOURCE[1]} = $0 ]]; then
  echo "This script should not be run directly"
  exit 1
fi

if [[ -n $_DT ]]; then
  var=${BASH_SOURCE[1]/#$_DT\//}
  var=__${var//\//_}
  if [ -n "${!var}" ]; then
    return
  fi
  eval $var=1
fi

